### ISSUE TITLE
title.html、intro.htmlのbodyを記述

### ISSUE THREAD

**Issue by s1f102201728** [s1f102201728/team-project#3]
title.htmlおよびintro.htmlのbodyを記述して下さい。
title.htmlは短めで数行の文章、intro.htmlは下記のサイトの文章をそのまま引用して適切に文献を記載して下さい。
https://www.monsterhunter.com/ja/about/
また、必要があればtitle.cssおよびintro.cssに変更を加えて下さい。
宜しくお願いします。

**Comment by s1f102201728** [comment]
ひとまず形としてヘッダーの実装が完了したので、#2以降のissueの作業に取り掛かることができます。
授業の想定では、今週は本来ガッツリ作業を進める週ではないですが来週も課題が若干多めに出されることが予想されるので、情報連携基礎実習レポートの〆切を過ぎた20(月)あたりから徐々に作業を開始してほしいと思っております。
宜しくお願いします。

**Comment by 1f10220187** [comment]
ヘッダーのやつはもう共有されてたりしますか？

**Comment by s1f102201728** [comment]
勝手がわからず共有されてませんでした。申し訳ないです。
ただいま共有できたかと思いますので確認宜しくお願いします。

**Comment by 1f10220187** [comment]
ありがとうございます

**Comment by 1f10220187** [comment]
なんとなくやってみたのですがアドバイス、意見あれば教えてほしいです

**Comment by s1f102201728** [comment]
とりあえずこれで大丈夫です
背景設定したらそれと同時にcolorを変えます
